//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paper_MetadataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Column
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Column()
        {
            this.RelationshipColumns = new HashSet<RelationshipColumns>();
            this.RelationshipColumns1 = new HashSet<RelationshipColumns>();
            this.TableDrivedEntity = new HashSet<TableDrivedEntity>();
        }
    
        public string Value { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<byte> TypeEnum { get; set; }
        public bool IsCustomColumn { get; set; }
        public bool IsDBCalculatedColumn { get; set; }
        public int ID { get; set; }
        public int TableID { get; set; }
        public string Name { get; set; }
        public bool DataEntryEnabled { get; set; }
        public bool SearchEnabled { get; set; }
        public bool DataEntryView { get; set; }
        public string Alias { get; set; }
        public bool PrimaryKey { get; set; }
        public bool IsIdentity { get; set; }
        public bool IsNull { get; set; }
        public string DefaultValue { get; set; }
        public string DataType { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual Table Table { get; set; }
        public virtual ColumnKeyValue ColumnKeyValue { get; set; }
        public virtual DateColumnType DateColumnType { get; set; }
        public virtual StringColumnType StringColumnType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationshipColumns> RelationshipColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationshipColumns> RelationshipColumns1 { get; set; }
        public virtual NumericColumnType NumericColumnType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDrivedEntity> TableDrivedEntity { get; set; }
    }
}
