//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paper_MetadataManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyIdeaEntities : DbContext
    {
        public MyIdeaEntities()
            : base("name=MyIdeaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Column> Column { get; set; }
        public virtual DbSet<ColumnKeyValue> ColumnKeyValue { get; set; }
        public virtual DbSet<ColumnKeyValueRange> ColumnKeyValueRange { get; set; }
        public virtual DbSet<DatabaseInformation> DatabaseInformation { get; set; }
        public virtual DbSet<DateColumnType> DateColumnType { get; set; }
        public virtual DbSet<DBSchema> DBSchema { get; set; }
        public virtual DbSet<DBServer> DBServer { get; set; }
        public virtual DbSet<ImplicitOneToOneRelationshipType> ImplicitOneToOneRelationshipType { get; set; }
        public virtual DbSet<ISARelationship> ISARelationship { get; set; }
        public virtual DbSet<ManyToManyRelationshipType> ManyToManyRelationshipType { get; set; }
        public virtual DbSet<ManyToOneRelationshipType> ManyToOneRelationshipType { get; set; }
        public virtual DbSet<OneToManyRelationshipType> OneToManyRelationshipType { get; set; }
        public virtual DbSet<Relationship> Relationship { get; set; }
        public virtual DbSet<RelationshipColumns> RelationshipColumns { get; set; }
        public virtual DbSet<RelationshipType> RelationshipType { get; set; }
        public virtual DbSet<StringColumnType> StringColumnType { get; set; }
        public virtual DbSet<SubToSuperRelationshipType> SubToSuperRelationshipType { get; set; }
        public virtual DbSet<SubUnionToUnionRelationshipType> SubUnionToUnionRelationshipType { get; set; }
        public virtual DbSet<SuperToSubRelationshipType> SuperToSubRelationshipType { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<TableDrivedEntity> TableDrivedEntity { get; set; }
        public virtual DbSet<UnionRelationshipType> UnionRelationshipType { get; set; }
        public virtual DbSet<UnionToSubUnionRelationshipType> UnionToSubUnionRelationshipType { get; set; }
        public virtual DbSet<ExplicitOneToOneRelationshipType> ExplicitOneToOneRelationshipType { get; set; }
        public virtual DbSet<NumericColumnType> NumericColumnType { get; set; }
    }
}
