//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paper_MetadataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationshipColumns
    {
        public int ID { get; set; }
        public int RelationshipID { get; set; }
        public Nullable<int> FirstSideColumnID { get; set; }
        public Nullable<int> SecondSideColumnID { get; set; }
        public string PrimarySideFixedValue { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual Column Column1 { get; set; }
        public virtual Relationship Relationship { get; set; }
    }
}
