//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paper_MetadataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table()
        {
            this.Column = new HashSet<Column>();
            this.TableDrivedEntity = new HashSet<TableDrivedEntity>();
        }
    
        public Nullable<bool> IsStructurReferencee { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> BatchDataEntry { get; set; }
        public Nullable<bool> IsReferenceTable { get; set; }
        public Nullable<bool> IsAssociativeTable { get; set; }
        public int DBSchemaID { get; set; }
        public Nullable<bool> IndependentDataEntry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Column> Column { get; set; }
        public virtual DBSchema DBSchema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDrivedEntity> TableDrivedEntity { get; set; }
    }
}
