//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paper_MetadataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionRelationshipType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnionRelationshipType()
        {
            this.SubUnionToUnionRelationshipType = new HashSet<SubUnionToUnionRelationshipType>();
            this.UnionToSubUnionRelationshipType = new HashSet<UnionToSubUnionRelationshipType>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsTolatParticipation { get; set; }
        public bool UnionHoldsKeys { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubUnionToUnionRelationshipType> SubUnionToUnionRelationshipType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnionToSubUnionRelationshipType> UnionToSubUnionRelationshipType { get; set; }
    }
}
