//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.TransitionAction = new HashSet<TransitionAction>();
        }
    
        public int ID { get; set; }
        public int ProcessID { get; set; }
        public short ActionTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> vwSelected { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual ICollection<TransitionAction> TransitionAction { get; set; }
    }
}
