//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityTarget_RoleType
    {
        public int ID { get; set; }
        public int ActivityTargetID { get; set; }
        public int RoleTypeID { get; set; }
    
        public virtual RoleType RoleType { get; set; }
        public virtual ActivityTarget ActivityTarget { get; set; }
    }
}
