//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityTarget
    {
        public ActivityTarget()
        {
            this.ActivityTarget_RoleType = new HashSet<ActivityTarget_RoleType>();
        }
    
        public int ID { get; set; }
        public int ActivityID { get; set; }
        public short TargetType { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ICollection<ActivityTarget_RoleType> ActivityTarget_RoleType { get; set; }
    }
}
