//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArchiveItem()
        {
            this.ArchiveItem_Tag = new HashSet<ArchiveItem_Tag>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int FileRepositoryID { get; set; }
        public short FileType { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> ThumbnailFileRepositoryID { get; set; }
        public short MainType { get; set; }
        public Nullable<long> FileSize { get; set; }
        public int MyDataItemID { get; set; }
        public Nullable<int> FolderID { get; set; }
    
        public virtual FileRepository FileRepository { get; set; }
        public virtual MyDataItem MyDataItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchiveItem_Tag> ArchiveItem_Tag { get; set; }
        public virtual FileRepository FileRepository1 { get; set; }
    }
}
