//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackendActionActivity
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<bool> ResultSensetive { get; set; }
        public short StepType { get; set; }
        public short Type { get; set; }
        public Nullable<int> TableDrivedEntityID { get; set; }
        public Nullable<int> CodeFunctionID { get; set; }
        public Nullable<int> DatabaseFunctionEntityID { get; set; }
    
        public virtual CodeFunction CodeFunction { get; set; }
        public virtual DatabaseFunction_TableDrivedEntity DatabaseFunction_TableDrivedEntity { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
    }
}
