//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeFunction_TableDrivedEntity_Parameters
    {
        public int CodeFunction_TableDrivedEntityID { get; set; }
        public int CodeFunctionParameterID { get; set; }
        public int ColumnID { get; set; }
        public int ID { get; set; }
    
        public virtual CodeFunction_TableDrivedEntity CodeFunction_TableDrivedEntity { get; set; }
        public virtual Column Column { get; set; }
        public virtual CodeFunctionParameter CodeFunctionParameter { get; set; }
    }
}
