//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnCustomFormula
    {
        public int ID { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public bool CalculateFormulaAsDefault { get; set; }
        public bool OnlyOnNewData { get; set; }
        public bool OnlyOnEmptyValue { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual Formula Formula { get; set; }
    }
}
