//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnPhrase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColumnPhrase()
        {
            this.Phrase = new HashSet<Phrase>();
        }
    
        public int ID { get; set; }
        public int ColumnID { get; set; }
        public string Value { get; set; }
        public string Operator { get; set; }
        public Nullable<int> EntitySearchColumnsID { get; set; }
    
        public virtual Column Column { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phrase> Phrase { get; set; }
        public virtual EntitySearchColumns EntitySearchColumns { get; set; }
    }
}
