//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnValueRange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColumnValueRange()
        {
            this.ColumnValueRangeDetails = new HashSet<ColumnValueRangeDetails>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EntityRelationshipTailID { get; set; }
        public Nullable<int> TagColumnID { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual Column Column1 { get; set; }
        public virtual EntityRelationshipTail EntityRelationshipTail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColumnValueRangeDetails> ColumnValueRangeDetails { get; set; }
    }
}
