//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnValueRange
    {
        public ColumnValueRange()
        {
            this.ColumnValueRangeDetails = new HashSet<ColumnValueRangeDetails>();
            this.UIColumnValueRange = new HashSet<UIColumnValueRange>();
        }
    
        public int ID { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual ICollection<ColumnValueRangeDetails> ColumnValueRangeDetails { get; set; }
        public virtual ICollection<UIColumnValueRange> UIColumnValueRange { get; set; }
    }
}
