//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrosstabReportColumns
    {
        public int ID { get; set; }
        public int EntityCrosstabReportID { get; set; }
        public int EntityListViewColumnsID { get; set; }
    
        public virtual EntityListViewColumns EntityListViewColumns { get; set; }
        public virtual EntityCrosstabReport EntityCrosstabReport { get; set; }
    }
}
