//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseFunction_TableDrivedEntity_Columns
    {
        public int DatabaseFunction_TableDrivedEntityID { get; set; }
        public int DatabaseFunctionParameterID { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public int ID { get; set; }
        public Nullable<short> FixedParamID { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual DatabaseFunction_TableDrivedEntity DatabaseFunction_TableDrivedEntity { get; set; }
        public virtual DatabaseFunctionParameter DatabaseFunctionParameter { get; set; }
    }
}
