//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataMenuRelationshipTail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataMenuRelationshipTail()
        {
            this.DataMenuRelTailSearchableReports = new HashSet<DataMenuRelTailSearchableReports>();
        }
    
        public int ID { get; set; }
        public int EntityRelationshipTailID { get; set; }
        public int DataMenuSettingID { get; set; }
    
        public virtual DataMenuSetting DataMenuSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataMenuRelTailSearchableReports> DataMenuRelTailSearchableReports { get; set; }
        public virtual EntityRelationshipTail EntityRelationshipTail { get; set; }
    }
}
