//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataLog()
        {
            this.EditDataItemColumnDetails = new HashSet<EditDataItemColumnDetails>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MyDataItemID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public short MainType { get; set; }
        public bool MajorFunctionException { get; set; }
        public Nullable<int> Duration { get; set; }
        public string LocationInfo { get; set; }
        public Nullable<System.Guid> PackageGuid { get; set; }
        public bool MinorFunctionException { get; set; }
        public string MajorFunctionExceptionMessage { get; set; }
        public Nullable<int> RelatedItemID { get; set; }
    
        public virtual LetterItemLog LetterItemLog { get; set; }
        public virtual MyDataItem MyDataItem { get; set; }
        public virtual EditDataItemExceptionLog EditDataItemExceptionLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EditDataItemColumnDetails> EditDataItemColumnDetails { get; set; }
    }
}
