//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLinkDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataLinkDefinition()
        {
            this.DataLinkDefinition_EntityRelationshipTail = new HashSet<DataLinkDefinition_EntityRelationshipTail>();
        }
    
        public int ID { get; set; }
        public int SecondSideEntityID { get; set; }
        public Nullable<bool> NotJointEntities { get; set; }
        public Nullable<int> FirstSideDataMenuID { get; set; }
        public Nullable<int> SecondSideDataMenuID { get; set; }
    
        public virtual DataMenuSetting DataMenuSetting { get; set; }
        public virtual DataMenuSetting DataMenuSetting1 { get; set; }
        public virtual EntityDataItemReport EntityDataItemReport { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataLinkDefinition_EntityRelationshipTail> DataLinkDefinition_EntityRelationshipTail { get; set; }
    }
}
