//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataMenuRelTailSearchableReports
    {
        public int ID { get; set; }
        public int DataMenuRelationshipTailID { get; set; }
        public int EntitySearchableReportID { get; set; }
        public string Group1 { get; set; }
    
        public virtual DataMenuRelationshipTail DataMenuRelationshipTail { get; set; }
        public virtual EntitySearchableReport EntitySearchableReport { get; set; }
    }
}
