//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataMenuSetting
    {
        public DataMenuSetting()
        {
            this.DataMenuDataViewRelationship = new HashSet<DataMenuDataViewRelationship>();
            this.DataMenuGridViewRelationship = new HashSet<DataMenuGridViewRelationship>();
            this.DataMenuReportRelationship = new HashSet<DataMenuReportRelationship>();
        }
    
        public int ID { get; set; }
    
        public virtual ICollection<DataMenuDataViewRelationship> DataMenuDataViewRelationship { get; set; }
        public virtual ICollection<DataMenuGridViewRelationship> DataMenuGridViewRelationship { get; set; }
        public virtual ICollection<DataMenuReportRelationship> DataMenuReportRelationship { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
    }
}
