//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataMenuSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataMenuSetting()
        {
            this.DataLinkDefinition = new HashSet<DataLinkDefinition>();
            this.DataMenuDataItemReport = new HashSet<DataMenuDataItemReport>();
            this.DataMenuForViewEntity = new HashSet<DataMenuForViewEntity>();
            this.DataMenuForViewEntity1 = new HashSet<DataMenuForViewEntity>();
            this.DataMenuRelationshipTail = new HashSet<DataMenuRelationshipTail>();
            this.EntityRelationshipTailDataMenuItems = new HashSet<EntityRelationshipTailDataMenuItems>();
            this.EntityReport = new HashSet<EntityReport>();
            this.TableDrivedEntity1 = new HashSet<TableDrivedEntity>();
        }
    
        public int ID { get; set; }
        public int TableDrivedEntityID { get; set; }
        public string Name { get; set; }
        public byte[] IconContent { get; set; }
        public Nullable<bool> AllowDataEntry { get; set; }
        public Nullable<bool> AllowArchive { get; set; }
        public Nullable<bool> AllowLetter { get; set; }
        public Nullable<bool> AllowWorkflowReport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataLinkDefinition> DataLinkDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataMenuDataItemReport> DataMenuDataItemReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataMenuForViewEntity> DataMenuForViewEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataMenuForViewEntity> DataMenuForViewEntity1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataMenuRelationshipTail> DataMenuRelationshipTail { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityRelationshipTailDataMenuItems> EntityRelationshipTailDataMenuItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityReport> EntityReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDrivedEntity> TableDrivedEntity1 { get; set; }
    }
}
