//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseFunctionParameter
    {
        public DatabaseFunctionParameter()
        {
            this.DatabaseFunction_TableDrivedEntity_Columns = new HashSet<DatabaseFunction_TableDrivedEntity_Columns>();
        }
    
        public int ID { get; set; }
        public int DatabaseFunctionID { get; set; }
        public string DataType { get; set; }
        public string ParamName { get; set; }
        public bool Enable { get; set; }
        public short InputOutput { get; set; }
        public Nullable<short> Order { get; set; }
    
        public virtual DatabaseFunction DatabaseFunction { get; set; }
        public virtual ICollection<DatabaseFunction_TableDrivedEntity_Columns> DatabaseFunction_TableDrivedEntity_Columns { get; set; }
    }
}
