//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataMenuForViewEntity
    {
        public int ID { get; set; }
        public int DataMenuSettingID { get; set; }
        public int RelationshipID { get; set; }
        public int TargetDataMenuSettingID { get; set; }
    
        public virtual DataMenuSetting DataMenuSetting { get; set; }
        public virtual DataMenuSetting DataMenuSetting1 { get; set; }
        public virtual Relationship Relationship { get; set; }
    }
}
