//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditDataItemColumnDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EditDataItemColumnDetails()
        {
            this.FormulaUsageParemeters = new HashSet<FormulaUsageParemeters>();
        }
    
        public int ID { get; set; }
        public int DataLogID { get; set; }
        public int ColumnID { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Info { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public string FormulaException { get; set; }
    
        public virtual DataLog DataLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaUsageParemeters> FormulaUsageParemeters { get; set; }
    }
}
