//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityReport
    {
        public int ID { get; set; }
        public int TableDrivedEntityID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<short> ReportType { get; set; }
        public Nullable<int> EntityListViewID { get; set; }
    
        public virtual EntityDataItemReport EntityDataItemReport { get; set; }
        public virtual EntityListView EntityListView { get; set; }
        public virtual EntitySearchableReport EntitySearchableReport { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        public virtual SecurityObject SecurityObject { get; set; }
    }
}
