//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityGroup()
        {
            this.EntityGroup_Relationship = new HashSet<EntityGroup_Relationship>();
            this.TransitionAction_EntityGroup = new HashSet<TransitionAction_EntityGroup>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ProcessID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityGroup_Relationship> EntityGroup_Relationship { get; set; }
        public virtual Process Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransitionAction_EntityGroup> TransitionAction_EntityGroup { get; set; }
    }
}
