//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityStateCondition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityStateCondition()
        {
            this.EntityState = new HashSet<EntityState>();
            this.EntityStateConditionSecuritySubject = new HashSet<EntityStateConditionSecuritySubject>();
            this.EntityStateConditionValues = new HashSet<EntityStateConditionValues>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public Nullable<int> EntityRelationshipTailID { get; set; }
        public Nullable<short> ValueOpoerator { get; set; }
        public Nullable<short> SecuritySubjectInOrNotIn { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual EntityRelationshipTail EntityRelationshipTail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityState> EntityState { get; set; }
        public virtual Formula Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityStateConditionSecuritySubject> EntityStateConditionSecuritySubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityStateConditionValues> EntityStateConditionValues { get; set; }
    }
}
