//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntitySecurityDirect
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int TableDrivedEntityID { get; set; }
        public Nullable<short> Mode { get; set; }
        public int TableDrivedEntityStateID { get; set; }
    
        public virtual EntityState EntityState { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
    }
}
