//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityListView
    {
        public EntityListView()
        {
            this.DataMenuSetting = new HashSet<DataMenuSetting>();
            this.EntityChartReport = new HashSet<EntityChartReport>();
            this.EntityCrosstabReport = new HashSet<EntityCrosstabReport>();
            this.EntityListReport = new HashSet<EntityListReport>();
            this.LetterTemplate = new HashSet<LetterTemplate>();
            this.EntityListViewColumns = new HashSet<EntityListViewColumns>();
            this.TableDrivedEntity1 = new HashSet<TableDrivedEntity>();
        }
    
        public int ID { get; set; }
        public int TableDrivedEntityID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<DataMenuSetting> DataMenuSetting { get; set; }
        public virtual ICollection<EntityChartReport> EntityChartReport { get; set; }
        public virtual ICollection<EntityCrosstabReport> EntityCrosstabReport { get; set; }
        public virtual ICollection<EntityListReport> EntityListReport { get; set; }
        public virtual ICollection<LetterTemplate> LetterTemplate { get; set; }
        public virtual ICollection<EntityListViewColumns> EntityListViewColumns { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        public virtual ICollection<TableDrivedEntity> TableDrivedEntity1 { get; set; }
    }
}
