//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityDataViewReport
    {
        public int ID { get; set; }
        public int DataMenuSettingID { get; set; }
        public int EntityListViewID { get; set; }
        public string temp { get; set; }
    
        public virtual DataMenuSetting DataMenuSetting { get; set; }
        public virtual EntityListView EntityListView { get; set; }
        public virtual EntitySearchableReport EntitySearchableReport { get; set; }
    }
}
