//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityState()
        {
            this.EntitySecurityDirect = new HashSet<EntitySecurityDirect>();
            this.FormulaItems = new HashSet<FormulaItems>();
            this.EntityStateSecuritySubject = new HashSet<EntityStateSecuritySubject>();
            this.EntityStateValues = new HashSet<EntityStateValues>();
            this.EntityState_UIActionActivity = new HashSet<EntityState_UIActionActivity>();
        }
    
        public int ID { get; set; }
        public int TableDrivedEntityID { get; set; }
        public string Title { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public Nullable<int> EntityRelationshipTailID { get; set; }
        public Nullable<short> ValueOpoerator { get; set; }
        public Nullable<short> SecuritySubjectInOrNotIn { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual EntityRelationshipTail EntityRelationshipTail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntitySecurityDirect> EntitySecurityDirect { get; set; }
        public virtual Formula Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaItems> FormulaItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityStateSecuritySubject> EntityStateSecuritySubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityStateValues> EntityStateValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityState_UIActionActivity> EntityState_UIActionActivity { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
    }
}
