//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityListReportSubsColumns
    {
        public int ID { get; set; }
        public int EntityListReportSubsID { get; set; }
        public int ParentEntityListViewColumnsID { get; set; }
        public int ChildEntityListViewColumnsID { get; set; }
    
        public virtual EntityListReportSubs EntityListReportSubs { get; set; }
        public virtual EntityListViewColumns EntityListViewColumns { get; set; }
        public virtual EntityListViewColumns EntityListViewColumns1 { get; set; }
    }
}
