//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntitySearch
    {
        public EntitySearch()
        {
            this.SearchRepository = new HashSet<SearchRepository>();
            this.TableDrivedEntity = new HashSet<TableDrivedEntity>();
            this.EntitySearchColumns = new HashSet<EntitySearchColumns>();
        }
    
        public int ID { get; set; }
        public int TableDrivedEntityID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<SearchRepository> SearchRepository { get; set; }
        public virtual ICollection<TableDrivedEntity> TableDrivedEntity { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity1 { get; set; }
        public virtual ICollection<EntitySearchColumns> EntitySearchColumns { get; set; }
    }
}
