//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityDirectlReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityDirectlReport()
        {
            this.EntityDirectlReportParameters = new HashSet<EntityDirectlReportParameters>();
        }
    
        public int ID { get; set; }
        public string URL { get; set; }
    
        public virtual EntityDataItemReport EntityDataItemReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityDirectlReportParameters> EntityDirectlReportParameters { get; set; }
    }
}
