//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntitySecurityCondition
    {
        public int ID { get; set; }
        public int EntitySecurityDirectID { get; set; }
        public Nullable<int> EntityRelationshipTailID { get; set; }
        public int ColumnID { get; set; }
        public short Operator { get; set; }
        public string Value { get; set; }
        public Nullable<int> DatabaseFunctionID { get; set; }
        public short ReservedValue { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual DatabaseFunction DatabaseFunction { get; set; }
        public virtual EntityRelationshipTail EntityRelationshipTail { get; set; }
        public virtual EntitySecurityDirect EntitySecurityDirect { get; set; }
    }
}
