//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formula()
        {
            this.ColumnCustomFormula = new HashSet<ColumnCustomFormula>();
            this.EntityValidation = new HashSet<EntityValidation>();
            this.PhraseColumn = new HashSet<PhraseColumn>();
            this.SavedPreDefinedSearchSimpleColumn = new HashSet<SavedPreDefinedSearchSimpleColumn>();
            this.TableDrivedEntityStateCondition = new HashSet<TableDrivedEntityStateCondition>();
            this.FormulaItems = new HashSet<FormulaItems>();
            this.FormulaItems1 = new HashSet<FormulaItems>();
            this.LetterTemplatePlainField = new HashSet<LetterTemplatePlainField>();
            this.State_Formula = new HashSet<State_Formula>();
            this.TransitionAction_Formula = new HashSet<TransitionAction_Formula>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TableDrivedEntityID { get; set; }
        public string Name { get; set; }
        public string ResultType { get; set; }
        public string Title { get; set; }
        public Nullable<int> CodeFunction_TableDrivedEntityID { get; set; }
        public Nullable<int> LinearFormulaID { get; set; }
        public Nullable<int> DatabaseFunction_TableDrivedEntityID { get; set; }
        public Nullable<int> CodeFunctionID { get; set; }
    
        public virtual CodeFunction CodeFunction { get; set; }
        public virtual CodeFunction_TableDrivedEntity CodeFunction_TableDrivedEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColumnCustomFormula> ColumnCustomFormula { get; set; }
        public virtual DatabaseFunction_TableDrivedEntity DatabaseFunction_TableDrivedEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityValidation> EntityValidation { get; set; }
        public virtual LinearFormula LinearFormula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhraseColumn> PhraseColumn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedPreDefinedSearchSimpleColumn> SavedPreDefinedSearchSimpleColumn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDrivedEntityStateCondition> TableDrivedEntityStateCondition { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaItems> FormulaItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaItems> FormulaItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterTemplatePlainField> LetterTemplatePlainField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State_Formula> State_Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransitionAction_Formula> TransitionAction_Formula { get; set; }
    }
}
