//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphDefinition
    {
        public GraphDefinition()
        {
            this.GraphDefinition_EntityRelationshipTail = new HashSet<GraphDefinition_EntityRelationshipTail>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> NotJointEntities { get; set; }
        public Nullable<int> FirstSideDataMenuID { get; set; }
    
        public virtual DataMenuSetting DataMenuSetting { get; set; }
        public virtual EntityDataItemReport EntityDataItemReport { get; set; }
        public virtual ICollection<GraphDefinition_EntityRelationshipTail> GraphDefinition_EntityRelationshipTail { get; set; }
    }
}
