//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Letter()
        {
            this.Letter1 = new HashSet<Letter>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FileRepositoryID { get; set; }
        public Nullable<int> LetterTemplateID { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
        public Nullable<bool> IsGeneratedOrSelected { get; set; }
        public int LetterTypeID { get; set; }
        public System.DateTime LetterDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> RelatedLetterID { get; set; }
        public bool FromExternalSource { get; set; }
        public string ExternalSourceKey { get; set; }
        public int MyDataItemID { get; set; }
        public int UserID { get; set; }
        public string LetterNumber { get; set; }
    
        public virtual FileRepository FileRepository { get; set; }
        public virtual MyDataItem MyDataItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Letter> Letter1 { get; set; }
        public virtual Letter Letter2 { get; set; }
    }
}
