//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterTemplatePlainField
    {
        public int ID { get; set; }
        public string FieldName { get; set; }
        public int LetterTemplateID { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public Nullable<int> EntityListViewColumnsID { get; set; }
    
        public virtual EntityListViewColumns EntityListViewColumns { get; set; }
        public virtual Formula Formula { get; set; }
        public virtual LetterTemplate LetterTemplate { get; set; }
    }
}
