//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LetterTemplate()
        {
            this.LetterTemplatePlainField = new HashSet<LetterTemplatePlainField>();
            this.LetterTemplateRelationshipField = new HashSet<LetterTemplateRelationshipField>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int TableDrivedEntityID { get; set; }
        public int EntityListViewID { get; set; }
    
        public virtual EntityListView EntityListView { get; set; }
        public virtual MainLetterTemplate MainLetterTemplate { get; set; }
        public virtual PartialLetterTemplate PartialLetterTemplate { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterTemplatePlainField> LetterTemplatePlainField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterTemplateRelationshipField> LetterTemplateRelationshipField { get; set; }
    }
}
