//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedServer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int SourceDBServerID { get; set; }
        public int TargetDBServerID { get; set; }
    
        public virtual DBServer DBServer { get; set; }
        public virtual DBServer DBServer1 { get; set; }
    }
}
