//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavigationTree
    {
        public NavigationTree()
        {
            this.NavigationTree1 = new HashSet<NavigationTree>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ItemTitle { get; set; }
        public int ItemIdentity { get; set; }
        public string Category { get; set; }
        public Nullable<int> TableDrivedEntityID { get; set; }
        public string Tooltip { get; set; }
        public string Name { get; set; }
    
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        public virtual ICollection<NavigationTree> NavigationTree1 { get; set; }
        public virtual NavigationTree NavigationTree2 { get; set; }
    }
}
