//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumericColumnType
    {
        public int ColumnID { get; set; }
        public Nullable<int> Precision { get; set; }
        public Nullable<int> Scale { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public bool Delimiter { get; set; }
    
        public virtual Column Column { get; set; }
    }
}
