//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationPost
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IsDeactive { get; set; }
        public Nullable<int> UserID { get; set; }
        public int OrganizationID { get; set; }
        public int OrganizationType_RoleTypeID { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual OrganizationType_RoleType OrganizationType_RoleType { get; set; }
        public virtual User User { get; set; }
        public virtual SecuritySubject SecuritySubject { get; set; }
    }
}
