//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.OrganizationPost = new HashSet<OrganizationPost>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int OrganizationTypeID { get; set; }
    
        public virtual OrganizationType OrganizationType { get; set; }
        public virtual ICollection<OrganizationPost> OrganizationPost { get; set; }
        public virtual SecuritySubject SecuritySubject { get; set; }
    }
}
