//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phrase
    {
        public int ID { get; set; }
        public Nullable<int> ParentLogicPhraseID { get; set; }
        public short Type { get; set; }
    
        public virtual PhraseLogic PhraseLogic { get; set; }
        public virtual PhraseColumn PhraseColumn { get; set; }
        public virtual PhraseLogic PhraseLogic1 { get; set; }
    }
}
