//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestAction()
        {
            this.Request = new HashSet<Request>();
            this.RequestAction1 = new HashSet<RequestAction>();
        }
    
        public int ID { get; set; }
        public int RequestID { get; set; }
        public int PossibleTransitionActionID { get; set; }
        public int PossibleTransitionID { get; set; }
        public int PossibleActionID { get; set; }
        public bool IsActive { get; set; }
        public bool IsCompleted { get; set; }
        public int TargetOrganizationPostID { get; set; }
        public string TargetReason { get; set; }
        public Nullable<int> DoerUserID { get; set; }
        public System.DateTime DateTimeCreation { get; set; }
        public Nullable<System.DateTime> DateTimeCompleted { get; set; }
        public Nullable<int> CausingRequestActionID { get; set; }
        public Nullable<int> LedToState { get; set; }
        public string Description { get; set; }
        public Nullable<int> StateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
        public virtual Request Request1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestAction> RequestAction1 { get; set; }
        public virtual RequestAction RequestAction2 { get; set; }
    }
}
