//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RequestAction1 = new HashSet<RequestAction>();
            this.RequestNote = new HashSet<RequestNote>();
        }
    
        public int ID { get; set; }
        public int ProcessID { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public int CurrentStateID { get; set; }
        public int CreatorUserID { get; set; }
        public Nullable<int> MyDataItemID { get; set; }
        public Nullable<int> LastRequestActionID { get; set; }
        public Nullable<int> CreatorOrganizationPostID { get; set; }
    
        public virtual MyDataItem MyDataItem { get; set; }
        public virtual RequestAction RequestAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestAction> RequestAction1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestNote> RequestNote { get; set; }
    }
}
