//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleType
    {
        public RoleType()
        {
            this.OrganizationType_RoleType = new HashSet<OrganizationType_RoleType>();
            this.TransitionActionTarget = new HashSet<TransitionActionTarget>();
            this.ActivityTarget_RoleType = new HashSet<ActivityTarget_RoleType>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsSuperAdmin { get; set; }
        public string ExternalKey { get; set; }
    
        public virtual ICollection<OrganizationType_RoleType> OrganizationType_RoleType { get; set; }
        public virtual ICollection<TransitionActionTarget> TransitionActionTarget { get; set; }
        public virtual ICollection<ActivityTarget_RoleType> ActivityTarget_RoleType { get; set; }
        public virtual SecuritySubject SecuritySubject { get; set; }
    }
}
