//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveAdvancedSearch
    {
        public int ID { get; set; }
        public int PhraseLogicID { get; set; }
        public string Temp { get; set; }
    
        public virtual PhraseLogic PhraseLogic { get; set; }
        public virtual SavedSearchRepository SavedSearchRepository { get; set; }
    }
}
