//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedSearchRepository
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SavedSearchRepository()
        {
            this.EntitySearchableReport = new HashSet<EntitySearchableReport>();
        }
    
        public int ID { get; set; }
        public bool IsPreDefinedOrAdvanced { get; set; }
        public string Title { get; set; }
        public int TableDrivedEntityID { get; set; }
        public Nullable<int> EntitySearchID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntitySearchableReport> EntitySearchableReport { get; set; }
        public virtual SaveAdvancedSearch SaveAdvancedSearch { get; set; }
        public virtual SavedPreDefinedSearch SavedPreDefinedSearch { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        public virtual EntitySearch EntitySearch { get; set; }
    }
}
