//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedPreDefinedSearchRelationship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SavedPreDefinedSearchRelationship()
        {
            this.SavedPreDefinedSearchRelationshipData = new HashSet<SavedPreDefinedSearchRelationshipData>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PreDefinedSearchID { get; set; }
        public Nullable<int> EntitySearchColumnsID { get; set; }
    
        public virtual EntitySearchColumns EntitySearchColumns { get; set; }
        public virtual SavedPreDefinedSearch SavedPreDefinedSearch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedPreDefinedSearchRelationshipData> SavedPreDefinedSearchRelationshipData { get; set; }
    }
}
