//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedPreDefinedSearchSimpleColumn
    {
        public int ID { get; set; }
        public int PreDefinedSearchID { get; set; }
        public string Value { get; set; }
        public int EntitySearchColumnsID { get; set; }
        public short Operator { get; set; }
        public Nullable<int> FormulaID { get; set; }
    
        public virtual EntitySearchColumns EntitySearchColumns { get; set; }
        public virtual Formula Formula { get; set; }
        public virtual SavedPreDefinedSearch SavedPreDefinedSearch { get; set; }
    }
}
