//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchRepository
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SearchRepository()
        {
            this.EntitySearchableReport = new HashSet<EntitySearchableReport>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SourceRelationID { get; set; }
        public Nullable<bool> HasNotRelationshipCheck { get; set; }
        public Nullable<int> RelationshipFromCount { get; set; }
        public Nullable<int> RelationshipToCount { get; set; }
        public Nullable<bool> IsSimpleSearch { get; set; }
        public int TableDrivedEntityID { get; set; }
        public Nullable<int> EntitySearchID { get; set; }
        public string Title { get; set; }
    
        public virtual EntitySearch EntitySearch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntitySearchableReport> EntitySearchableReport { get; set; }
        public virtual LogicPhrase LogicPhrase { get; set; }
        public virtual Relationship Relationship { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
    }
}
