//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityObject
    {
        public SecurityObject()
        {
            this.Permission = new HashSet<Permission>();
        }
    
        public int ID { get; set; }
        public short Type { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual DatabaseInformation DatabaseInformation { get; set; }
        public virtual DBSchema DBSchema { get; set; }
        public virtual EntityCommand EntityCommand { get; set; }
        public virtual EntityReport EntityReport { get; set; }
        public virtual Relationship Relationship { get; set; }
        public virtual SubSystems SubSystems { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        public virtual ICollection<Permission> Permission { get; set; }
    }
}
