//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class State_Formula
    {
        public int ID { get; set; }
        public int StateID { get; set; }
        public int FormulaID { get; set; }
        public string Message { get; set; }
        public bool TrueFalse { get; set; }
    
        public virtual Formula Formula { get; set; }
        public virtual State State { get; set; }
    }
}
