//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperToSubRelationshipType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuperToSubRelationshipType()
        {
            this.SuperToSubDeterminerValue = new HashSet<SuperToSubDeterminerValue>();
            this.TableDrivedEntity = new HashSet<TableDrivedEntity>();
        }
    
        public int ID { get; set; }
        public int ISARelationshipID { get; set; }
        public Nullable<int> SuperEntityDeterminerColumnID { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual ISARelationship ISARelationship { get; set; }
        public virtual RelationshipType RelationshipType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuperToSubDeterminerValue> SuperToSubDeterminerValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDrivedEntity> TableDrivedEntity { get; set; }
    }
}
