//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDrivedEntityStateCondition
    {
        public TableDrivedEntityStateCondition()
        {
            this.TableDrivedEntityStateConditionSecuritySubject = new HashSet<TableDrivedEntityStateConditionSecuritySubject>();
            this.TableDrivedEntityStateConditionValues = new HashSet<TableDrivedEntityStateConditionValues>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int TableDrivedEntityStateID { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public Nullable<int> EntityRelationshipTailID { get; set; }
        public Nullable<short> ValueOpoerator { get; set; }
        public Nullable<short> SecuritySubjectInOrNotIn { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual EntityRelationshipTail EntityRelationshipTail { get; set; }
        public virtual Formula Formula { get; set; }
        public virtual TableDrivedEntityState TableDrivedEntityState { get; set; }
        public virtual ICollection<TableDrivedEntityStateConditionSecuritySubject> TableDrivedEntityStateConditionSecuritySubject { get; set; }
        public virtual ICollection<TableDrivedEntityStateConditionValues> TableDrivedEntityStateConditionValues { get; set; }
    }
}
