//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDrivedEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableDrivedEntity()
        {
            this.ArchiveFolder = new HashSet<ArchiveFolder>();
            this.ArchiveTag = new HashSet<ArchiveTag>();
            this.EntityArchiveRelationshipTails = new HashSet<EntityArchiveRelationshipTails>();
            this.EntityLetterRelationshipTails = new HashSet<EntityLetterRelationshipTails>();
            this.ArcRelationshipGroup = new HashSet<ArcRelationshipGroup>();
            this.BackendActionActivity = new HashSet<BackendActionActivity>();
            this.CodeFunction_TableDrivedEntity = new HashSet<CodeFunction_TableDrivedEntity>();
            this.DatabaseFunction_TableDrivedEntity = new HashSet<DatabaseFunction_TableDrivedEntity>();
            this.DataLinkDefinition = new HashSet<DataLinkDefinition>();
            this.DataMenuSetting = new HashSet<DataMenuSetting>();
            this.EntityDeterminer = new HashSet<EntityDeterminer>();
            this.EntityListView = new HashSet<EntityListView>();
            this.EntityRelationshipTail = new HashSet<EntityRelationshipTail>();
            this.EntityRelationshipTail1 = new HashSet<EntityRelationshipTail>();
            this.EntityRelationshipTailDataMenuItems = new HashSet<EntityRelationshipTailDataMenuItems>();
            this.EntityReport = new HashSet<EntityReport>();
            this.EntityUIComposition = new HashSet<EntityUIComposition>();
            this.EntityValidation = new HashSet<EntityValidation>();
            this.Formula = new HashSet<Formula>();
            this.LetterTemplate = new HashSet<LetterTemplate>();
            this.LetterType = new HashSet<LetterType>();
            this.NavigationTree = new HashSet<NavigationTree>();
            this.Relationship = new HashSet<Relationship>();
            this.Relationship1 = new HashSet<Relationship>();
            this.SearchRepository = new HashSet<SearchRepository>();
            this.Process = new HashSet<Process>();
            this.TableDrivedEntity_EntityCommand = new HashSet<TableDrivedEntity_EntityCommand>();
            this.UIActionActivity = new HashSet<UIActionActivity>();
            this.EntitySecurityDirect = new HashSet<EntitySecurityDirect>();
            this.TableDrivedEntity_Columns = new HashSet<TableDrivedEntity_Columns>();
            this.TableDrivedEntityState = new HashSet<TableDrivedEntityState>();
            this.EntitySearch = new HashSet<EntitySearch>();
        }
    
        public int ID { get; set; }
        public int TableID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> IndependentDataEntry { get; set; }
        public bool BatchDataEntry { get; set; }
        public Nullable<bool> IsDataReference { get; set; }
        public bool IsStructurReferencee { get; set; }
        public bool IsAssociative { get; set; }
        public bool IsDisabled { get; set; }
        public bool IsReadonly { get; set; }
        public Nullable<bool> SearchInitially { get; set; }
        public bool LoadArchiveRelatedItems { get; set; }
        public string Color { get; set; }
        public bool LoadLetterRelatedItems { get; set; }
        public bool IsOrginal { get; set; }
        public bool IsView { get; set; }
        public bool Reviewed { get; set; }
        public string Description { get; set; }
        public bool ColumnsReviewed { get; set; }
        public bool SelectAsComboBox { get; set; }
        public Nullable<int> DeterminerColumnID { get; set; }
        public Nullable<int> DataMenuSettingID { get; set; }
        public Nullable<int> InternalTableSuperToSubRelID { get; set; }
        public bool Removed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchiveFolder> ArchiveFolder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchiveTag> ArchiveTag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityArchiveRelationshipTails> EntityArchiveRelationshipTails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityLetterRelationshipTails> EntityLetterRelationshipTails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArcRelationshipGroup> ArcRelationshipGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackendActionActivity> BackendActionActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeFunction_TableDrivedEntity> CodeFunction_TableDrivedEntity { get; set; }
        public virtual Column Column { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatabaseFunction_TableDrivedEntity> DatabaseFunction_TableDrivedEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataLinkDefinition> DataLinkDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataMenuSetting> DataMenuSetting { get; set; }
        public virtual DataMenuSetting DataMenuSetting1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityDeterminer> EntityDeterminer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityListView> EntityListView { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityRelationshipTail> EntityRelationshipTail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityRelationshipTail> EntityRelationshipTail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityRelationshipTailDataMenuItems> EntityRelationshipTailDataMenuItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityReport> EntityReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityUIComposition> EntityUIComposition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityValidation> EntityValidation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formula> Formula { get; set; }
        public virtual LetterEnabledEntities LetterEnabledEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterTemplate> LetterTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterType> LetterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NavigationTree> NavigationTree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationship> Relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationship> Relationship1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchRepository> SearchRepository { get; set; }
        public virtual SuperToSubRelationshipType SuperToSubRelationshipType { get; set; }
        public virtual Table Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Process> Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDrivedEntity_EntityCommand> TableDrivedEntity_EntityCommand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UIActionActivity> UIActionActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntitySecurityDirect> EntitySecurityDirect { get; set; }
        public virtual SecurityObject SecurityObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDrivedEntity_Columns> TableDrivedEntity_Columns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDrivedEntityState> TableDrivedEntityState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntitySearch> EntitySearch { get; set; }
    }
}
