//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDrivedEntityState
    {
        public TableDrivedEntityState()
        {
            this.EntityState_UIActionActivity = new HashSet<EntityState_UIActionActivity>();
            this.FormulaItems = new HashSet<FormulaItems>();
            this.EntitySecurityDirectStates = new HashSet<EntitySecurityDirectStates>();
            this.TableDrivedEntityStateSecuritySubject = new HashSet<TableDrivedEntityStateSecuritySubject>();
            this.TableDrivedEntityStateValues = new HashSet<TableDrivedEntityStateValues>();
        }
    
        public int ID { get; set; }
        public int TableDrivedEntityID { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public string Title { get; set; }
        public Nullable<short> EntityStateOperator { get; set; }
        public Nullable<int> EntityRelationshipTailID { get; set; }
        public Nullable<int> SecuritySubjectID { get; set; }
        public Nullable<short> SecuritySubjectOperator { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual EntityRelationshipTail EntityRelationshipTail { get; set; }
        public virtual ICollection<EntityState_UIActionActivity> EntityState_UIActionActivity { get; set; }
        public virtual Formula Formula { get; set; }
        public virtual ICollection<FormulaItems> FormulaItems { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        public virtual ICollection<EntitySecurityDirectStates> EntitySecurityDirectStates { get; set; }
        public virtual ICollection<TableDrivedEntityStateSecuritySubject> TableDrivedEntityStateSecuritySubject { get; set; }
        public virtual ICollection<TableDrivedEntityStateValues> TableDrivedEntityStateValues { get; set; }
    }
}
