//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransitionAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransitionAction()
        {
            this.TransitionActionTarget = new HashSet<TransitionActionTarget>();
            this.TransitionAction_EntityGroup = new HashSet<TransitionAction_EntityGroup>();
            this.TransitionAction_Formula = new HashSet<TransitionAction_Formula>();
        }
    
        public int ID { get; set; }
        public int TransitionID { get; set; }
        public bool MultipleUserEnabled { get; set; }
        public string Name { get; set; }
        public Nullable<short> ActionTypeID { get; set; }
    
        public virtual Transition Transition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransitionActionTarget> TransitionActionTarget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransitionAction_EntityGroup> TransitionAction_EntityGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransitionAction_Formula> TransitionAction_Formula { get; set; }
    }
}
