//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransitionActivity
    {
        public int TransitionID { get; set; }
        public int ActivityID { get; set; }
        public Nullable<bool> Dummy { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Transition Transition { get; set; }
    }
}
