//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIEnablityDetails
    {
        public int ID { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public Nullable<bool> Readonly { get; set; }
        public Nullable<int> UIActionActivityID { get; set; }
        public Nullable<int> RelationshipID { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual Relationship Relationship { get; set; }
        public virtual UIActionActivity UIActionActivity { get; set; }
    }
}
